version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    command: ["dotnet", "monitoramento_ambiental_mongodb.dll"]
    restart: always
