name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release

      - name: Build Docker image
        run: |
          docker build -t wagnersimonetto/monitoramento_ambiental_mgdb:v1 .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push wagnersimonetto/monitoramento_ambiental_mgdb:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via FTP
        uses: SebastienC/ftp-deploy-action@v1.1
        with:
        server: 'ftps://waws-prod-blu-323.ftp.azurewebsites.windows.net'
        username: ${{ secrets.AZURE_FTP_USERNAME }}
        password: ${{ secrets.AZURE_FTP_PASSWORD }}
        local-dir: './build'
        remote-dir: '/'

